import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../models/bank_account.dart';
import '../data/earnings_providers.dart';
import '../../dashboard/data/dashboard_providers.dart';

class BankAccountScreen extends ConsumerStatefulWidget {
  const BankAccountScreen({super.key});
  @override
  ConsumerState<BankAccountScreen> createState() => _BankAccountScreenState();
}

class _BankAccountScreenState extends ConsumerState<BankAccountScreen> {
  final _formKey = GlobalKey<FormState>();
  final _holderC = TextEditingController();
  final _accountC = TextEditingController();
  final _confirmC = TextEditingController();
  final _ifscC = TextEditingController();
  final _bankC = TextEditingController();
  BankAccountType _type = BankAccountType.savings;

  @override
  void dispose() { _holderC.dispose(); _accountC.dispose(); _confirmC.dispose(); _ifscC.dispose(); _bankC.dispose(); super.dispose(); }

  void _save() async {
    if (!_formKey.currentState!.validate()) return;
    if (_accountC.text != _confirmC.text) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Account numbers do not match'), behavior: SnackBarBehavior.floating));
      return;
    }
    
    final accountsAsync = ref.read(bankAccountsProvider);
    final isPrimary = accountsAsync.value?.isEmpty ?? true;

    final account = BankAccount(
      id: '', // Generated by Firestore
      holderName: _holderC.text.trim(),
      accountNumber: _accountC.text.trim(),
      ifscCode: _ifscC.text.trim().toUpperCase(),
      bankName: _bankC.text.trim(),
      accountType: _type,
      isVerified: false,
      isPrimary: isPrimary,
      createdAt: DateTime.now(),
    );

    try {
      await ref.read(firestoreServiceProvider).addBankAccount(account);
      if (mounted) context.go('/earnings');
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(icon: const Icon(Icons.arrow_back), onPressed: () => context.go('/earnings')),
        title: const Text('Link Bank Account', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SingleChildScrollView(padding: const EdgeInsets.all(20),
        child: Form(key: _formKey, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          _label('Account Holder Name'),
          TextFormField(controller: _holderC, decoration: const InputDecoration(hintText: 'Full name as per bank'),
            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null),
          const SizedBox(height: 16),
          _label('Account Number'),
          TextFormField(controller: _accountC, keyboardType: TextInputType.number,
            decoration: const InputDecoration(hintText: 'Account number'),
            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null),
          const SizedBox(height: 16),
          _label('Confirm Account Number'),
          TextFormField(controller: _confirmC, keyboardType: TextInputType.number,
            decoration: const InputDecoration(hintText: 'Re-enter account number'),
            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null),
          const SizedBox(height: 16),
          _label('IFSC Code'),
          TextFormField(controller: _ifscC, textCapitalization: TextCapitalization.characters,
            decoration: const InputDecoration(hintText: 'e.g. SBIN0001234'),
            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null),
          const SizedBox(height: 16),
          _label('Bank Name'),
          TextFormField(controller: _bankC, decoration: const InputDecoration(hintText: 'e.g. State Bank of India'),
            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null),
          const SizedBox(height: 20),
          _label('Account Type'),
          const SizedBox(height: 8),
          SegmentedButton<BankAccountType>(
            segments: const [
              ButtonSegment(value: BankAccountType.savings, label: Text('Savings')),
              ButtonSegment(value: BankAccountType.current, label: Text('Current')),
            ],
            selected: {_type}, onSelectionChanged: (s) => setState(() => _type = s.first),
            style: ButtonStyle(backgroundColor: WidgetStateProperty.resolveWith((states) =>
              states.contains(WidgetState.selected) ? theme.colorScheme.primary.withValues(alpha: 0.2) : Colors.transparent)),
          ),
          const SizedBox(height: 32),
          ElevatedButton(onPressed: _save, child: const Text('LINK ACCOUNT')),
        ]))),
    );
  }

  Widget _label(String text) => Padding(padding: const EdgeInsets.only(bottom: 6),
    child: Text(text, style: TextStyle(fontWeight: FontWeight.w600, color: Colors.grey[400], fontSize: 13)));
}
